version: '3'
services:
  postgres:
    image: postgres:12.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tracker
    volumes:
      - ./postgres:/var/lib/postgresql/data
